services:
  - type: web
    name: n-grami
    env: python
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn test_web:app --host 0.0.0.0 --port $PORT"
